// ============================================================
// Jarvis SOC — Notification Engine
// Email (nodemailer) + Slack (webhook) + Desktop
// All channels optional — skip silently if not configured.
// ============================================================

const nodemailer = require('nodemailer');
const fetch = require('node-fetch');

// ---- Config from .env ----
const EMAIL_FROM = process.env.EMAIL_FROM || '';
const EMAIL_TO = process.env.EMAIL_TO || '';
const EMAIL_APP_PASSWORD = process.env.EMAIL_APP_PASSWORD || '';
const SLACK_WEBHOOK_URL = process.env.SLACK_WEBHOOK_URL || '';

const emailConfigured = !!(EMAIL_FROM && EMAIL_TO && EMAIL_APP_PASSWORD);
const slackConfigured = !!SLACK_WEBHOOK_URL;

// ---- Rate Limiting ----
let lastEmailTime = 0;
let lastSlackTime = 0;
let emailCountToday = 0;
let slackCountToday = 0;
let lastResetDay = new Date().getDate();

const EMAIL_COOLDOWN_MS = 60000;   // 1 per minute
const SLACK_COOLDOWN_MS = 30000;   // 1 per 30 seconds
const MAX_EMAILS_PER_DAY = 20;
const MAX_SLACK_PER_DAY = 40;

function resetDailyCountsIfNeeded() {
  const today = new Date().getDate();
  if (today !== lastResetDay) {
    emailCountToday = 0;
    slackCountToday = 0;
    lastResetDay = today;
  }
}

// ---- Email Transport ----
let transporter = null;
if (emailConfigured) {
  transporter = nodemailer.createTransport({
    service: 'gmail',
    auth: {
      user: EMAIL_FROM,
      pass: EMAIL_APP_PASSWORD,
    },
  });
}

// ---- Pending email batch ----
let emailBatch = [];
let emailBatchTimer = null;

/**
 * Send an alert notification to all configured channels.
 * @param {Object} alert - { severity, title, id, details, cvssScore, mitreTechnique, source }
 */
async function notify(alert) {
  resetDailyCountsIfNeeded();

  const promises = [];

  if (emailConfigured) {
    promises.push(sendEmail(alert).catch(err => {
      console.error(`  [Notifier] Email error: ${err.message}`);
    }));
  }

  if (slackConfigured) {
    promises.push(sendSlack(alert).catch(err => {
      console.error(`  [Notifier] Slack error: ${err.message}`);
    }));
  }

  if (promises.length > 0) {
    await Promise.allSettled(promises);
  }
}

// ---- Email ----

async function sendEmail(alert) {
  if (!transporter) return;
  if (emailCountToday >= MAX_EMAILS_PER_DAY) return;

  const now = Date.now();
  if (now - lastEmailTime < EMAIL_COOLDOWN_MS) {
    // Batch it
    emailBatch.push(alert);
    if (!emailBatchTimer) {
      emailBatchTimer = setTimeout(flushEmailBatch, EMAIL_COOLDOWN_MS);
    }
    return;
  }

  lastEmailTime = now;
  emailCountToday++;

  const severityColors = {
    CRITICAL: '#dc2626', HIGH: '#ea580c', MEDIUM: '#ca8a04',
    LOW: '#2563eb', INFO: '#6b7280',
  };
  const color = severityColors[alert.severity] || '#6b7280';

  const html = `
    <div style="font-family: 'Segoe UI', Arial, sans-serif; max-width: 600px; margin: 0 auto; background: #0B1F33; border-radius: 12px; overflow: hidden;">
      <div style="background: #0B1F33; padding: 24px 32px; border-bottom: 3px solid #0FA3A3;">
        <h1 style="color: #fff; margin: 0; font-size: 20px;">🛡️ JARVIS SOC ALERT</h1>
      </div>
      <div style="padding: 24px 32px; background: #1a1a2e;">
        <div style="display: inline-block; background: ${color}; color: #fff; padding: 4px 12px; border-radius: 4px; font-weight: bold; font-size: 14px; margin-bottom: 16px;">
          ${alert.severity}
        </div>
        <h2 style="color: #e2e8f0; margin: 8px 0 16px;">${alert.title || 'Alert'}</h2>
        <table style="width: 100%; color: #94a3b8; font-size: 14px;">
          <tr><td style="padding: 4px 0; width: 120px;"><strong>Alert ID:</strong></td><td>${alert.id || 'N/A'}</td></tr>
          <tr><td style="padding: 4px 0;"><strong>CVSS Score:</strong></td><td>${alert.cvssScore || 'N/A'}</td></tr>
          <tr><td style="padding: 4px 0;"><strong>MITRE:</strong></td><td>${alert.mitreTechnique || 'N/A'}</td></tr>
          <tr><td style="padding: 4px 0;"><strong>Source:</strong></td><td>${alert.source || 'Jarvis'}</td></tr>
          <tr><td style="padding: 4px 0;"><strong>Time:</strong></td><td>${new Date().toISOString()}</td></tr>
        </table>
        ${alert.details ? `<p style="color: #cbd5e1; margin-top: 16px; font-size: 14px; line-height: 1.5;">${alert.details}</p>` : ''}
        <div style="margin-top: 24px; padding: 12px; background: #0f172a; border-radius: 6px; text-align: center;">
          <span style="color: #0FA3A3; font-size: 13px;">Log in to your Jarvis dashboard for full details</span>
        </div>
      </div>
      <div style="padding: 12px 32px; background: #0B1F33; text-align: center;">
        <span style="color: #475569; font-size: 12px;">Generated by Jarvis Autonomous SOC Agent</span>
      </div>
    </div>
  `;

  await transporter.sendMail({
    from: `"Jarvis SOC" <${EMAIL_FROM}>`,
    to: EMAIL_TO,
    subject: `[JARVIS ALERT] ${alert.severity}: ${alert.title || 'Security Alert'}`,
    html,
  });

  console.log(`  [Notifier] Email sent: ${alert.severity} — ${alert.title}`);
}

async function flushEmailBatch() {
  emailBatchTimer = null;
  if (emailBatch.length === 0) return;

  const batch = [...emailBatch];
  emailBatch = [];

  // Combine into single email
  const combined = {
    severity: batch.reduce((max, a) => {
      const order = { CRITICAL: 5, HIGH: 4, MEDIUM: 3, LOW: 2, INFO: 1 };
      return (order[a.severity] || 0) > (order[max] || 0) ? a.severity : max;
    }, 'INFO'),
    title: `${batch.length} alerts batched`,
    details: batch.map(a => `[${a.severity}] ${a.title}`).join('\n'),
    id: 'BATCH',
  };

  await sendEmail(combined).catch(err => {
    console.error(`  [Notifier] Batch email error: ${err.message}`);
  });
}

// ---- Slack ----

async function sendSlack(alert) {
  if (!SLACK_WEBHOOK_URL) return;
  if (slackCountToday >= MAX_SLACK_PER_DAY) return;

  const now = Date.now();
  if (now - lastSlackTime < SLACK_COOLDOWN_MS) return;

  lastSlackTime = now;
  slackCountToday++;

  const severityEmoji = {
    CRITICAL: '🔴', HIGH: '🟠', MEDIUM: '🟡', LOW: '🔵', INFO: '⚪',
  };
  const emoji = severityEmoji[alert.severity] || '⚪';
  const mention = alert.severity === 'CRITICAL' ? '<!here> ' : '';

  const payload = {
    blocks: [
      {
        type: 'header',
        text: { type: 'plain_text', text: `${emoji} JARVIS ALERT — ${alert.severity}`, emoji: true },
      },
      {
        type: 'section',
        text: { type: 'mrkdwn', text: `${mention}*${alert.title || 'Security Alert'}*\nID: \`${alert.id || 'N/A'}\`` },
      },
      {
        type: 'section',
        fields: [
          { type: 'mrkdwn', text: `*CVSS Score:*\n${alert.cvssScore || 'N/A'}` },
          { type: 'mrkdwn', text: `*MITRE Technique:*\n${alert.mitreTechnique || 'N/A'}` },
          { type: 'mrkdwn', text: `*Time:*\n${new Date().toLocaleString()}` },
          { type: 'mrkdwn', text: `*Source:*\n${alert.source || 'Jarvis'}` },
        ],
      },
    ],
  };

  if (alert.details) {
    payload.blocks.push({
      type: 'section',
      text: { type: 'mrkdwn', text: `\`\`\`${alert.details.substring(0, 500)}\`\`\`` },
    });
  }

  await fetch(SLACK_WEBHOOK_URL, {
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    body: JSON.stringify(payload),
  });

  console.log(`  [Notifier] Slack sent: ${alert.severity} — ${alert.title}`);
}

// ---- Status ----

function getStatus() {
  return {
    email: emailConfigured ? 'configured' : 'not configured',
    slack: slackConfigured ? 'configured' : 'not configured',
    emailsSentToday: emailCountToday,
    slacksSentToday: slackCountToday,
    emailsRemaining: MAX_EMAILS_PER_DAY - emailCountToday,
    slacksRemaining: MAX_SLACK_PER_DAY - slackCountToday,
  };
}

/**
 * Send a test notification to all configured channels.
 */
async function sendTestNotification() {
  const testAlert = {
    severity: 'INFO',
    title: 'Jarvis Test Notification',
    id: 'TEST-' + Date.now(),
    details: 'This is a test notification from Jarvis SOC Agent. All channels are operational.',
    source: 'test',
    cvssScore: 'N/A',
    mitreTechnique: 'N/A',
  };

  const results = {};

  if (emailConfigured) {
    try {
      // Force send (bypass cooldown for test)
      lastEmailTime = 0;
      await sendEmail(testAlert);
      results.email = 'sent';
    } catch (err) {
      results.email = `failed: ${err.message}`;
    }
  } else {
    results.email = 'not configured';
  }

  if (slackConfigured) {
    try {
      lastSlackTime = 0;
      await sendSlack(testAlert);
      results.slack = 'sent';
    } catch (err) {
      results.slack = `failed: ${err.message}`;
    }
  } else {
    results.slack = 'not configured';
  }

  return results;
}

module.exports = {
  notify,
  sendEmail,
  sendSlack,
  sendTestNotification,
  getStatus,
};
